# fly.toml app configuration file generated for proaka-backend-server on 2024-12-08T18:36:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proaka-backend--server'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
[mounts]
  source = "pg_data"  # 正しいボリューム名を指定
  destination = "/var/lib/postgresql/data"


